export const ORACLE = {
  header: {
    root: "oracle-header",
    nav: (id) => `nav-link-${id}`,
    ctaEnquire: "header-enquire-btn",
    mobileMenuToggle: "mobile-menu-toggle",
    mobileMenu: "mobile-menu",
  },
  hero: {
    root: "hero-section",
    ctaPrimary: "hero-cta-enquire",
    ctaSecondary: "hero-cta-floorplans",
    tagline: "hero-tagline",
  },
  about: { root: "about-section" },
  manifesto: { root: "manifesto-section", item: (i) => `manifesto-item-${i}` },
  residences: {
    root: "residences-section",
    table: "residences-table",
    row: (i) => `residence-row-${i}`,
    enquireBtn: (i) => `residence-enquire-${i}`,
  },
  floorPlans: {
    root: "floor-plans-section",
    item: (i) => `floor-plan-${i}`,
    download: (i) => `floor-plan-download-${i}`,
  },
  gallery: { root: "gallery-section", item: (i) => `gallery-item-${i}` },
  specs: { root: "specs-section" },
  amenities: { root: "amenities-section", item: (i) => `amenity-${i}` },
  location: { root: "location-section" },
  founder: { root: "founder-section" },
  enquiry: {
    root: "enquiry-section",
    form: "enquiry-form",
    fullName: "enquiry-full-name",
    mobile: "enquiry-mobile",
    email: "enquiry-email",
    propertyType: "enquiry-property-type",
    budget: "enquiry-budget",
    submit: "enquiry-submit",
    success: "enquiry-success",
  },
  footer: { root: "footer-section" },
  floating: { whatsapp: "floating-whatsapp", call: "floating-call" },
};
